### ISSUE TITLE
Next Version Roadmap

### ISSUE THREAD

**Issue by Xinayder** [RockyTV/duality-git#1]
### BUGS
- The plugin crashes if you run Duality without a loaded project;
### TO-DO
- [ ] Allow users to specify when to commit;
- [ ] Only stage modified/added/removed files;
- [x] Pretty write the .gitignore file
